baseURL = "http://brycekellogg.com"
languageCode = "en-us"
title = "Bryce Kellogg"
publishDir = "docs"

[params]
  AnalyticsCode = 'UA-55873386-1'

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = -110

  [[menu.main]]
    name = "Publications"
    url = "/Publications/"
    weight = -100

  [[menu.main]]
    name = "Patents"
    url = "/Patents/"
    weight = -95

  [[menu.main]]
    name = "Github"
    url = "https://github.com/brycekellogg"
    weight = -90

  [[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/brycekellogg/"
    weight = -80
